config/routes.rb
Rails.application.routes.draw do
  resources :forecasts
  post 'messages', to: 'messages#create'
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forecast.rb
class Forecast < ApplicationRecord
  
  def get_weather_data        
  ForecastIO.forecast(lat, lng)  
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  after_create_commit {
    MessageBroadcastJob.perform_later(self)
  }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # validates :is_online?, inclusion: [true, false] # add this line
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  def username
      #@users = User.is_online?
      #@users = onlinename
      #return email.split('@')[0].capitalize
      return onlinename
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  def index
  end

end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :set_forecast, only: [:show, :edit, :update, :destroy]

  # GET /forecasts
  # GET /forecasts.json
  def index
    @forecasts = Forecast.all
  end

  # GET /forecasts/1
  # GET /forecasts/1.json
  def show       
    @weather = @forecast.get_weather       
    @current_weather = @weather.currently  

    @daily_weather = @weather.daily.data.first(1)
  end

  # GET /forecasts/new
  def new
    @forecast = Forecast.new
  end

  # GET /forecasts/1/edit
  def edit
  end

  # POST /forecasts
  # POST /forecasts.json
  def create
    @forecast = Forecast.new(forecast_params)

    respond_to do |format|
      if @forecast.save
        format.html { redirect_to @forecast, notice: 'Forecast was successfully created.' }
        format.json { render :show, status: :created, location: @forecast }
      else
        format.html { render :new }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forecasts/1
  # PATCH/PUT /forecasts/1.json
  def update
    respond_to do |format|
      if @forecast.update(forecast_params)
        format.html { redirect_to @forecast, notice: 'Forecast was successfully updated.' }
        format.json { render :show, status: :ok, location: @forecast }
      else
        format.html { render :edit }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forecasts/1
  # DELETE /forecasts/1.json
  def destroy
    @forecast.destroy
    respond_to do |format|
      format.html { redirect_to forecasts_url, notice: 'Forecast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forecast
      @forecast = Forecast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forecast_params
      params.require(:forecast).permit(:lat, :lng)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  def create
    @message = Message.new(message_params)
    @message.user = current_user  
    @message.save
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #before_action :authenticate_user! <-- this fucked up the way it looked when you hit site... wtf... 
  def home
    @messages = Message.last(10)
    @message = Message.new
    @users = User.all
  end

  def index

  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def sign_up_params
    params.require(:user).permit(:onlinename,:email,:password,:password_confirmation,:is_online?)
  end

  def edituser
    params.require(:edituser).permit(:onlinename,:email,:password,:password_confirmation,:current_password,:is_online?)
  end


end

app/controllers/userlist_controller.rb
class UserlistController < ApplicationController
  #attr_accessible :is_online?

  def user
    @users = onlinename.all
    @user = User.all
    #@users = is_online?.find(params[:user_id])
    @message.user = current_user 
  end

  def edituser
    @users = current_user
    @users = onlinename.all
  end

  # def is_online?(is_online?)
  #   is_online?.exists?(is_online?: 'true')
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/userlist_helper.rb
module UserlistHelper
end

app/views/forecasts/_form.html.erb
<%= simple_form_for(@forecast) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :lat %>
    <%= f.input :lng %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/forecasts/edit.html.erb
<h1>Editing Forecast</h1>

<%= render 'form', forecast: @forecast %>

<%= link_to 'Show', @forecast %> |
<%= link_to 'Back', forecasts_path %>

app/views/forecasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forecasts</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forecasts.each do |forecast| %>
      <tr>
        <td><%= forecast.lat %></td>
        <td><%= forecast.lng %></td>
        <td><%= link_to 'Show', forecast %></td>
        <td><%= link_to 'Edit', edit_forecast_path(forecast) %></td>
        <td><%= link_to 'Destroy', forecast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forecast', new_forecast_path %>

app/views/forecasts/new.html.erb
<h1>New Forecast</h1>

<%= render 'form', forecast: @forecast %>

<%= link_to 'Back', forecasts_path %>

app/views/forecasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @forecast.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @forecast.lng %>
</p>

<%= link_to 'Edit', edit_forecast_path(@forecast) %> |
<%= link_to 'Back', forecasts_path %>

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= value %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom navbar-light bg-light">
  <a class="navbar-brand">myChat! - Developed by:</a>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
  <%= link_to "Brett Simington", href="https://github.com/brettsimington", class:"nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd">
  <a class="navbar-brand" href="<%= root_path %>">myChat!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if current_user %>  
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.onlinename %> 
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <!--<#%= link_to "Edit Account", edit_user_registration_path, class: 'dropdown-item' %#>-->
          <div class="dropdown-divider"></div>
          <%= link_to "Sign out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </div>
        
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Create Account", new_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">  
        <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_userlist.html.erb
<% if user_signed_in? %>
<div class="userlist">
<!-- script to refresh user list? -->
<script>

</script>
<!-- script to refresh user list? -->
  
<div class="card" style="width: 12rem;">
  <div class="card-header">
    Users Online
  </div>
  <ul class="list-group list-group-flush">
    <!-- logic to show is user is online -->
   <% @users.each do |user| %>
   <% if user.is_online? %>
      <li class="list-group-item"><%= image_tag("on.png")%> <%= user.onlinename %></li>
      <% end %>
      <% end %>
    <!-- logic to show is user is online -->
  </ul>
</div>
      
<br />

<div class="card" style="width: 12rem;">
  <div class="card-header">
    Users Offline
  </div>
  <ul class="list-group list-group-flush">
    <!-- logic to show is user is offline -->
   <% @users.each do |user| %>
   <% if !user.is_online? %>
    <li class="list-group-item"><%= image_tag("off.png")%> <%= user.onlinename %></li>
    <% end %>
    <% end %>
    <!-- logic to show is user is offline -->
  </ul>
</div>
<% end %>
</div>

app/views/layouts/_weather.html.erb
<div class="weather">
  <script>
$(document).ready(function(){
  $("#submitCity").click(function(){
    getWeather();
  });
});
function getWeather(city){
  var city = $("#city").val();
  var key = '8707a3816ca4237392460dd8c74bd3ff'
  var temp = $(".temp");
  var htemp = $(".htemp");
  var ltemp = $(".ltemp");
  var desc = $(".desc");
  var wind = $(".wind");
  var icon = $(".icon");
  if(city != ''){
    fetch('https://api.openweathermap.org/data/2.5/weather?q='+ city + '&units=imperial' + '&appid=' + key) 
     .then(function(resp) { return resp.json() }) // Convert data to json
     .then(function(data) {
     console.log(data);
     temp.html(data.main.temp+" F");
     htemp.html(data.main.temp_max+" F");
     ltemp.html(data.main.temp_min+" F");
     desc.html(data.weather[0].description); //<-- why no worky? I think because weather -> 0 -> description... how read inside of 0?
     wind.html(data.wind.speed);
     icon.attr("src", "http://openweathermap.org/img/wn/" + data.weather[0].icon+".png");
     })
     .catch(function() {
    // catch any errors
  });
  }
  window.onload = function() {
    weatherBallon( Tampa );
}
};
</script>
  <% if user_signed_in? %>
  <div class="card" style="width: 14rem;">
    <div class="card-header">
      Local Weather!
      <%= image_tag("weather.png")%>
    </div>
    <div class="card-header">
      Enter City
      <div class="row form-group form-inline" id="cityDiv"></div>
        <input type="text" name="city" id="city" class="form-control" placeholder="Enter City Name">
        <button id="submitCity" class="btn btn-primary">Search</button>
    </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Cur Temp: <h7 class="temp"></h7></li>
        <li class="list-group-item">High Temp: <h7 class="htemp"></h7></li>
        <li class="list-group-item">Low Temp: <h7 class="ltemp"></h7></li>
        <li class="list-group-item">Conditions: <h7 class="desc"></h7><img class="icon"></li>
        <li class="list-group-item">Wind Speed: <h7 class="wind"></h7></li>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>myChat</title>
    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if user_signed_in? %>
      <%= tag :meta, name: "current-user", data: {id: current_user.id} %>
    <% end %>

  </head>
  <body>
    <!-- I found online, by rendering things like navbar, footer, alerts, i am not flooding my code with code.. Brett -->
  <div class="empty">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/userlist' %>
    <%= render 'layouts/weather' %>
    <%= render 'layouts/footer' %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="well">
  <%= message.created_at.strftime("%I:%M %p") %> <%= message.user.username %>: <%= message.body %>
</div>

app/views/messages/create.js.erb
//$('#chatbox').append("<%= j render @message %>");
$('#message_body').val('');

app/views/pages/home.html.erb
<div class="content">
<% if user_signed_in? %>
<!-- play here to modify the alerts. hide / fade etc.. -->
<script>
    $(document).ready(function() {
      $(".alert-warning").hide();
    });
</script>
<!-- -->
<!-- beggining of bootstrap jumbotron and the messabe box where teh chat appears -->
<div class="jumbotron">
  <h1 style="text-align: center"> <%= image_tag("favicon.png")%> myChat!</h1>
  <div class="well" id="chatbox" style="height:250px; border: solid 1px #222222; overflow-y: scroll">
    <% @messages.each do |message| %>
      <%= render 'messages/message', message: message %>
    <% end %>
  </div>
  
  <%= form_with model: @message do |f| %>
  <div class="input-group mb-3">
    <%= f.text_field :body, placeholder: "Say something...", class: "form-control" %>
    <div class="input-group-append">
      <%= f.submit "Send", class: "btn btn-info" %>
    </div>
  </div>
  <% end %>
  <% else %>
  <p style="text-align: center">
    You need to be <%= link_to "Signed in", new_user_session_path %> in order to use myChat!
  </p>
  <% end %>
</div>
</div>

app/views/pages/index.html.erb
<h1>hello</h1>